export const Colors = {
  primary: 'black',
  barStyle: 'dark-content',
  backdropColor: '#00000020',
  backgroundColor: '#fff',
  tabBarColor: '#fff',
  darkTextColor: '#fff',
  textcolor: '#000',
  mediumTextColor: '#000',
  lightTextColor: '#aaaaaa',
  buttonRippleColor: '#e3ffed',
  cardMediumBackgroundColor: '#fff',
  statusbar: '#E4FDF0',
  statusBarLight: '#E4FDF0',
  cardColor: '#fff',
  switchBackgroundColor: 'rgba(102, 114, 229, 0.15)',
  cardBorderColor:'#e3ffed',
  customFieldBackground: '#ffffff',
  themeColor: '#33d16b',
  backgroundColorLight: '#fdfdfd',
  backgroundThemeColor: '#fff',
  saveTextColor: '#6672e5',
  appSecondaryColor: '#6672e5',
  appThirdColor: '#fff',
  splashBackground:'#ffffff',

  mainHeadingColor: '#1f1f1f',
  appTextColor: '#fff',
  selectedItemBg: '#e3ffed',
  selectedItemBorder: '#33d16b',
  mediumIconColor: '#999999',
  nameColor: '#222222',
  BusinessOptionBorderColor: '#e4e7e7',
  BusinessOptionBorderTopColor: '#c8d5d2',
  BusinessOptionBorderBottomColor: '#dedede',
  borderColorPicker: '#dddddd',
  assetBackgroundColor: '#e3ffed',
  textColorHome: '#777777',
  modalBgColor: '#ffffff',

  //constant colors
  white: '#ffffff',
  black: '#000',
  lightBorderColor: '#eeeeee',
};