export const SAVE_USER = 'SAVE_USER';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SET_BUSINESS_ID = 'SET_BUSINESS_ID';
export const SET_LOADING = 'SET_LOADING';
export const SET_LAUNCH_DATA = 'SET_LAUNCH_DATA';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const SET_SERVICE_STORE_URL = 'SET_SERVICE_STORE_URL';
export const SET_WEBVIEW_COOKIES = 'SET_WEBVIEW_COOKIES';
export const SET_IS_MAINROUTE = 'SET_IS_MAINROUTE';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const SET_BUSINESS_DETAILS = 'SET_BUSINESS_DETAILS';
export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS';
export const SET_INITIAL_ROUTE = 'SET_INITIAL_ROUTE';
export const SET_OPENED_VIA_NOTIFICATION = 'SET_OPENED_VIA_NOTIFICATION';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_IS_ONLINE = 'SET_IS_ONLINE';
export const SET_MULTILOCATIONS_DOMAIN = 'SET_MULTILOCATIONS_DOMAIN';











